# MODELO DE K-MEDIAS

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer


# Carga de la información

In [2]:
df= pd.read_csv("https://raw.githubusercontent.com/lvherrerab/Sectorizaci-n-de-contratos-p-blicos-en-Colombia/main/OUTPUT/muestra_sincont_todas_varia.csv")

/var/folders/x_/qk792zrs1j99glg4nzk35j2m0000gn/T/ipykernel_4272/2029262373.py:1: DtypeWarning: Columns (69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("https://raw.githubusercontent.com/lvherrerab/Sectorizaci-n-de-contratos-p-blicos-en-Colombia/main/OUTPUT/muestra_sincont_todas_varia.csv")


# Preprocesamiento

In [3]:

# Crear un vectorizador TF-IDF
tfidf_vectorizer = TfidfVectorizer()

# Calcular la matriz TF-IDF
tfidf_matrix = tfidf_vectorizer.fit_transform(df['objeto_del_contrato'])

# Obtener los términos (palabras) del vocabulario
terms = tfidf_vectorizer.get_feature_names_out()

# Mostrar la matriz TF-IDF y el vocabulario
print(tfidf_matrix.toarray())
print(terms)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['00' '000' '0000' ... 'útica' 'útil' 'útiles']


# Modelo

In [4]:
from sklearn.cluster import KMeans

# Crear una instancia del modelo K-Means con el número deseado de clusters (K)
kmeans = KMeans(n_clusters=24)

# Ajustar el modelo a tus datos
kmeans.fit(tfidf_matrix)

# Asignar etiquetas de cluster a cada documento
labels = kmeans.labels_

# Puedes acceder a los centroides de los clusters si lo deseas
centroids = kmeans.cluster_centers_

# Visualizar las etiquetas asignadas a cada documento
print(labels)


/Users/linaherrera/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[ 2  2 10 ...  5 16  5]


In [5]:
np.shape(labels)

(48689,)

In [6]:
result = pd.concat([df, pd.DataFrame(labels)], axis=1)

# Métrica de desempeño

## Inercia

In [ ]:
# Inercia: Este valor proporcionará una medida de cuán cerca están los puntos de sus respectivos centroides,
# un valor pequeño indica que los clusters son más compactos y mejor definidos. 

inercia = kmeans.inertia_

print("Inercia del modelo K-Means:", inercia)

In [ ]:
## 