# LIBRERIAS

In [2]:
import pandas as pd
import numpy as np

In [22]:
df= pd.read_csv("https://raw.githubusercontent.com/lvherrerab/Sectorizaci-n-de-contratos-p-blicos-en-Colombia/main/OUTPUT/muestra_sin_contexto.csv")

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer


# Crear un vectorizador TF-IDF
tfidf_vectorizer = TfidfVectorizer()

# Calcular la matriz TF-IDF
tfidf_matrix = tfidf_vectorizer.fit_transform(df['objeto_del_contrato'])

# Obtener los términos (palabras) del vocabulario
terms = tfidf_vectorizer.get_feature_names_out()

# Mostrar la matriz TF-IDF y el vocabulario
print(tfidf_matrix.toarray())
print(terms)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['aaa' 'aaakfdm' 'aaakfea' ... 'zunigar' 'zura' 'zón']


In [26]:
from sklearn.cluster import KMeans

# Crear una instancia del modelo K-Means con el número deseado de clusters (K)
kmeans = KMeans(n_clusters=24)

# Ajustar el modelo a tus datos
kmeans.fit(tfidf_matrix)

# Asignar etiquetas de cluster a cada documento
labels = kmeans.labels_

# Puedes acceder a los centroides de los clusters si lo deseas
centroids = kmeans.cluster_centers_

# Visualizar las etiquetas asignadas a cada documento
print(labels)


/Users/linaherrera/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[ 6  7  7 ... 22  6  2]


In [27]:
np.shape(labels)

(49952,)

In [28]:
result = pd.concat([df, pd.DataFrame(labels)], axis=1)

In [29]:
result

objeto_del_contrato   0
0      ['aunar', 'esfuerzo', 'recurso', 'recuperacion...   6
1      ['adquisicion', 'mobiliario', 'unidad', 'admin...   7
2      ['suministrar', 'material', 'formacion', 'area...   7
3      ['contratar', 'prestacion', 'servicio', 'activ...   1
4      ['atender', 'sitio', 'critico', 'red', 'tercia...   7
...                                                  ...  ..
49947  ['aunar', 'esfuerzo', 'administrativo', 'logis...   6
49948  ['prestacion', 'servicio', 'publico', 'educati...   5
49949  ['prestar', 'servicio', 'profesional', 'especi...  22
49950  ['aunar', 'esfuerzo', 'recurso', 'tecnico', 'f...   6
49951  ['prestar', 'servicio', 'educacion', 'inicial'...   2

[49952 rows x 2 columns]

In [18]:
df["sector"].unique()

array(['Ambiente y Desarrollo Sostenible', 'Ciencia Tecnología',
       'Cultura', 'Educación Nacional', 'Hacienda y Crédito Público',
       'Inclusión Social y Reconciliación', 'Industria',
       'Información Estadística',
       'Inteligencia Estratégica y Contrainteligencia', 'Ley de Justicia',
       'Minas y Energía', 'No aplica/No pertenece', 'Planeación',
       'Presidencia de la República', 'Relaciones Exteriores',
       'Salud y Protección Social', 'Servicio Público',
       'Tecnologías de la Información y las Comunicaciones', 'Trabajo',
       'Transporte', 'Vivienda, Ciudad y Territorio', 'agricultura',
       'defensa', 'deportes', 'interior'], dtype=object)

In [21]:
df.groupby("sector").count()

nombre_entidad  \
sector                                                               
Ambiente y Desarrollo Sostenible                               631   
Ciencia Tecnología                                              18   
Cultura                                                        310   
Educación Nacional                                             628   
Hacienda y Crédito Público                                     155   
Inclusión Social y Reconciliación                              290   
Industria                                                      175   
Información Estadística                                         22   
Inteligencia Estratégica y Contrainteligencia                    1   
Ley de Justicia                                                258   
Minas y Energía                                                169   
No aplica/No pertenece                                        2248   
Planeación                                                     169   
Presidencia de la República                                     43   
Relaciones Exteriores                                           38   
Salud y Protección Social                                     2112   
Servicio Público                                              3576   
Tecnologías de la Información y las Comunicaciones             147   
Trabajo                                                        243   
Transporte                                                     917   
Vivienda, Ciudad y Territorio                                  364   
agricultura                                                    325   
defensa                                                        810   
deportes                                                       226   
interior                                                        61   

                                                    nit_entidad  departamento  \
sector                                                                          
Ambiente y Desarrollo Sostenible                            631           631   
Ciencia Tecnología                                           18            18   
Cultura                                                     310           310   
Educación Nacional                                          628           628   
Hacienda y Crédito Público                                  155           155   
Inclusión Social y Reconciliación                           290           290   
Industria                                                   175           175   
Información Estadística                                      22            22   
Inteligencia Estratégica y Contrainteligencia                 1             1   
Ley de Justicia                                             258           258   
Minas y Energía                                             169           169   
No aplica/No pertenece                                     2248          2248   
Planeación                                                  169           169   
Presidencia de la República                                  43            43   
Relaciones Exteriores                                        38            38   
Salud y Protección Social                                  2112          2112   
Servicio Público                                           3576          3576   
Tecnologías de la Información y las Comunicaciones          147           147   
Trabajo                                                     243           243   
Transporte                                                  917           917   
Vivienda, Ciudad y Territorio                               364           364   
agricultura                                                 325           325   
defensa                                                     810           810   
deportes                                                    226           226   
interior                                               

# Métrica de desempeño

In [17]:
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

# Datos
X = tfidf_matrix
Y = 

# Método del Codo
varianza_intra_cluster = []
silhouettes = []
for k in range(1, 80):  # Puedes ajustar el rango según tu preferencia
    kmeans = KMeans(n_clusters=k, random_state=123, n_init=10)
    kmeans.fit(X)
    varianza_intra_cluster.append(kmeans.inertia_)
    try:
        silhouette = silhouette_score(X, kmeans.labels_)
    except:
        silhouette = 0 # El índice de Silhouette sólo se puede calcular cuando se tiene K>1
    silhouettes.append(silhouette)
    Y[k] = kmeans.labels_


    
varianza_intra_cluster = []
silhouettes = []
for k in range (1, 11): # Evaluamos entre 1 a 11 clusters posibles
    kmeans = KMeans(n_clusters = k, random_state = 123, n_init=10).fit(tfidf_matrix)
    varianza_intra_cluster.append(kmeans.inertia_)
    try:
        silhouette = silhouette_score(tfidf_matrix, kmeans.labels_)
    except:
        silhouette = 0 # El índice de Silhouette sólo se puede calcular cuando se tiene K>1
    silhouettes.append(silhouette)
    Y[k] = kmeans.labels_

NameError: name 'Y' is not defined